export class Typography {
  static readonly fontSizeXs: number = 11;
  static readonly fontSizeSm: number = 12;
  static readonly fontSizeMd: number = 13;
  static readonly fontSizeBase: number = 14;
  static readonly fontSizeLg: number = 16;
  static readonly fontSizeXl: number = 18;
  static readonly fontSizeXxl: number = 22;
  static readonly fontSizeTitle: number = 28;

  static readonly fontWeightRegular: number = 400;
  static readonly fontWeightMedium: number = 500;
  static readonly fontWeightSemiBold: number = 600;
  static readonly fontWeightBold: number = 700;

  static readonly lineHeightTight: number = 1.2;
  static readonly lineHeightNormal: number = 1.5;
}
